"""Spend-matched discrete baselines for the absolute-q procurement model.

The primary fair granularity comparison keeps all clients active, matching the
current continuous absolute-q experiment. Each client may therefore choose only

    q_k in {0, q_k^repair}.

This is a strict subset of the continuous feasible set q_k >= 0.  The monetary
cap is supplied explicitly, so the intended ablation first solves the
continuous mechanism, records its realized payment B_con, then solves this
discrete problem under exactly the same cap B_con.

Because the discrete actions are indivisible, the best feasible allocation may
leave some of B_con unused.  That remainder is structural granularity loss, not
an extra advantage: burning it as a transfer would not change data or learning.
"""
import numpy as np

from .mechanism_absolute import client_cost, objective, package


def _evaluate(z,bits,repair):
    bits=np.asarray(bits,dtype=bool)
    q=np.where(bits,repair,0.0)
    active=np.ones(len(bits),dtype=bool)
    return float(objective(z,active,q)),q


def solve_discrete_repair_matched(z, spending_cap, restarts=64, seed=2026,
                                  max_rounds=60, tol=1e-12):
    """Heuristic all-active discrete repair solver under a matched spend cap.

    All clients remain active.  The only per-client choices are real-only
    (q=0) and exact label repair (q=q_repair).  Hence this feasible set is a
    strict subset of the continuous all-active q>=0 model.
    """
    K=len(z['n'])
    active=np.ones(K,dtype=bool)
    repair=np.asarray(z['repair_q'],dtype=float)
    base=np.asarray(z['base_cost'],dtype=float)
    base_total=float(base.sum())
    cap=float(spending_cap)
    if cap < base_total-tol:
        return dict(status='infeasible',matched_spending_cap=cap,
                    reason='matched cap below all-client real-data cost')

    full_cost=np.asarray(client_cost(z,repair,active),dtype=float)
    incremental=full_cost-base

    def feasible(bits):
        return base_total+float(incremental[np.asarray(bits,dtype=bool)].sum()) <= cap+1e-10

    def value(bits):
        return _evaluate(z,bits,repair)[0]

    starts=[]
    zero=np.zeros(K,dtype=bool)
    starts.append(zero)
    j0=value(zero)

    # Static solo-gain seeds.
    solo=[]
    for k in range(K):
        b=zero.copy(); b[k]=True
        if feasible(b):
            gain=j0-value(b)
            solo.append((gain/max(float(incremental[k]),1e-15),gain,k))
    for mode in (0,1):
        order=[t[2] for t in sorted(solo,key=lambda x:(x[mode],x[1]),reverse=True)]
        b=zero.copy()
        for k in order:
            trial=b.copy(); trial[k]=True
            if feasible(trial): b=trial
        starts.append(b)

    # Dynamic greedy seed: at each step add the feasible repair that gives the
    # largest immediate objective decrease, independent of whether it spends
    # the whole cap.
    b=zero.copy(); cur=value(b)
    while True:
        best=None
        for k in np.flatnonzero(~b):
            trial=b.copy(); trial[k]=True
            if not feasible(trial): continue
            v=value(trial)
            if v < cur-tol and (best is None or v<best[0]): best=(v,trial)
        if best is None: break
        cur,b=best
    starts.append(b)

    rng=np.random.default_rng(seed)
    # Random feasible seeds generated by random order packing.  These are cheap
    # and provide substantially different discrete patterns at K=30.
    for _ in range(int(restarts)):
        b=zero.copy()
        for k in rng.permutation(K):
            if rng.random()<0.65:
                trial=b.copy(); trial[k]=True
                if feasible(trial): b=trial
        starts.append(b)

    best_bits=None; best_val=np.inf
    seen=set()
    for start in starts:
        key=tuple(start.tolist())
        if key in seen: continue
        seen.add(key)
        b=start.copy(); cur=value(b)
        for _ in range(int(max_rounds)):
            incumbent_val=cur; incumbent=b
            on=np.flatnonzero(b); off=np.flatnonzero(~b)

            # One-bit moves permit both adding and removing repair states.
            for k in range(K):
                trial=b.copy(); trial[k]=~trial[k]
                if not feasible(trial): continue
                v=value(trial)
                if v < incumbent_val-tol:
                    incumbent_val=v; incumbent=trial

            # Swaps are important when the spend cap blocks all single adds.
            on_order=rng.permutation(on)
            off_order=rng.permutation(off)
            for i in on_order:
                for j in off_order:
                    trial=b.copy(); trial[i]=False; trial[j]=True
                    if not feasible(trial): continue
                    v=value(trial)
                    if v < incumbent_val-tol:
                        incumbent_val=v; incumbent=trial

            if incumbent is b: break
            b=incumbent; cur=incumbent_val

        if cur < best_val:
            best_val=cur; best_bits=b.copy()

    q=np.where(best_bits,repair,0.0)
    result=package(z,active,q,
        heuristic_note=('all clients fixed active; q_k restricted to {0, q_repair_k}; '
                        'matched monetary cap equals the realized continuous payment; '
                        'multi-start add/drop/swap local search, no global certificate'))
    realized=float(result['total_payment'])
    result.update(
        baseline='spend-matched all-active discrete repair',
        matched_spending_cap=cap,
        unused_matched_budget=float(max(0.0,cap-realized)),
        matched_budget_utilization=float(realized/cap) if cap>0 else 0.0,
        repaired_clients=int(best_bits.sum()),
        raw_clients=int(K-best_bits.sum()),
        discrete_state=['repair' if v else 'raw' for v in best_bits.tolist()],
        strict_subset_of_continuous=True,
        solver='multi-start add/drop/swap discrete local search')
    return result
